### ISSUE TITLE
Hey, ich hab ein kleines Problem

### ISSUE THREAD

**Issue by Random5156** [Fausti/mudlet-mg-profil#2]
Vielleicht kannst du mir ja weiterhelfen. 
Also ich habe deine Skripte runtergeladen und alle xml Dateien eingefügt. Soweit klappt auch alles. 

Leider ist es so, dass die Map jedesmal verschwindet, sobald ich mich auslogge. Ich hab zwar den Befehl "'#map save" benutzt und es steht auch, dass dieser erfolgreich ist, aber das laden klappt dann nicht. Da steht dann immer [FAIL]. Ich muss also immer wieder neu alles abklappern. 

Bin noch nicht so lang dabei. Dachte hab vllt was falsch gemacht. Also bei der Installation. Ich hab den Ordner einfach in Downloads entpackt und dann alle XML Dateien mit dem Skript Editor einzelnd eingefügt. Das wars eigentlich schon.

**Comment by Fausti** [comment]
Du hast nichts verkehrt gemacht :) Ist mein Fehler.

Öffne mal die ui_and_automapper.xml und ziemlich weit oben findest du eine Zeile:

filePath = "D:/Morgengrauen/",

Dort trägst du den Pfad zu einem Verzeichnis auf deiner Festplatte ein, der auch existiert. Beim Speichern der Karte lasse ich nicht prüfen ob das Speichern geklappt hat, während ich beim Laden das dann doch teste^^ Er speichert die Karte bei dir einfach nicht.

Die Änderung müsstest du auch per Skripteditor durchführen können. Bin da jetzt mittlerweile bissl raus weil ich an nem eigenen Clienten arbeite. Sag mal obs geklappt hat, wenn nicht muss ich das hier mal nachstellen.

**Comment by Random5156** [comment]
Hey,


habs grad mal probiert und es hat funktioniert.

 

Danke für die schnelle Antwort.


Gesendet: Dienstag, 17. Dezember 2019 um 21:09 Uhr
Von: "Matthias Faust" <notifications@github.com>
An: Fausti/mudlet-mg-profil <mudlet-mg-profil@noreply.github.com>
Cc: Random5156 <Riddle931@gmx.de>, Author <author@noreply.github.com>
Betreff: Re: [Fausti/mudlet-mg-profil] Hey, ich hab ein kleines Problem (#2)


Du hast nichts verkehrt gemacht :) Ist mein Fehler.

Öffne mal die ui_and_automapper.xml und ziemlich weit oben findest du eine Zeile:

filePath = "D:/Morgengrauen/",

Dort trägst du den Pfad zu einem Verzeichnis auf deiner Festplatte ein, der auch existiert. Beim Speichern der Karte lasse ich nicht prüfen ob das Speichern geklappt hat, während ich beim Laden das dann doch teste^^ Er speichert die Karte bei dir einfach nicht.

Die Änderung müsstest du auch per Skripteditor durchführen können. Bin da jetzt mittlerweile bissl raus weil ich an nem eigenen Clienten arbeite. Sag mal obs geklappt hat, wenn nicht muss ich das hier mal nachstellen.
